<h1> TESTING PYTHON <h1>

In [1]:
print ('HAHAHA')

HAHAHA

<h1> INSTALLING LIBRARIES <h1>

In [2]:
#numpy

In [3]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.2.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB5-StudentPC03\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [4]:
#pandas

In [5]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.2.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB5-StudentPC03\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [6]:
#matplotlib

In [7]:
pip install matplotlib

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.2.2)
Requirement already satisfied: packaging>=20.0 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB5-StudentPC03\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [8]:
#seaborn

In [9]:
pip install seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: seaborn in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: pandas>=1.2 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.2.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas>=1.2->seaborn) (2024.2)
Requirement already satisfied: six>=1.5 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB5-StudentPC03\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

<h1> Importing Libraries <h1>

In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

<h1> IMPORT PENGUIN DATA SET <h1>

In [11]:
early_bird = pd.read_csv('dataset\\penguins.csv')

In [12]:
early_bird

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [13]:
early_bird['weight_kilo'] = np.round (early_bird['body_mass_g'] / 1000, 1 )

In [14]:
early_bird

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight_kilo
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.8
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.8
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.4
...,...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009,4.0
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009,3.4
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009,3.8
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009,4.1
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009,3.8

<h1> BASIC CHECKING AND DESCRIPTIVE ANALYTICS </h1>

.info()
.describe()

In [15]:
early_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
 7   year               344 non-null    int64
 8   weight_kilo        342 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 24.3+ KB

In [16]:
early_bird.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,year,weight_kilo
count,342.000000,342.000000,342.000000,342.000000,344.000000,342.000000
mean,43.921930,17.151170,200.915205,4201.754386,2008.029070,4.202047
std,5.459584,1.974793,14.061714,801.954536,0.818356,0.803089
min,32.100000,13.100000,172.000000,2700.000000,2007.000000,2.700000
25%,39.225000,15.600000,190.000000,3550.000000,2007.000000,3.600000
50%,44.450000,17.300000,197.000000,4050.000000,2008.000000,4.000000
75%,48.500000,18.700000,213.000000,4750.000000,2009.000000,4.800000
max,59.600000,21.500000,231.000000,6300.000000,2009.000000,6.300000

In [17]:
#to flip the descriptive table // transpose

In [18]:
early_bird.describe().T

,count,mean,std,min,25%,50%,75%,max
bill_length_mm,342.0,43.921930,5.459584,32.1,39.225,44.45,48.5,59.6
bill_depth_mm,342.0,17.151170,1.974793,13.1,15.600,17.30,18.7,21.5
flipper_length_mm,342.0,200.915205,14.061714,172.0,190.000,197.00,213.0,231.0
body_mass_g,342.0,4201.754386,801.954536,2700.0,3550.000,4050.00,4750.0,6300.0
year,344.0,2008.029070,0.818356,2007.0,2007.000,2008.00,2009.0,2009.0
weight_kilo,342.0,4.202047,0.803089,2.7,3.600,4.00,4.8,6.3

<h1> DATA EXPLORATION </h1>

In [19]:
early_bird['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [20]:
early_bird['island'].value_counts()

island
Biscoe       168
Dream        124
Torgersen     52
Name: count, dtype: int64

<h1>DOES THE ADELIE PENGUIN LIVE EXCLUSIVELY ON AN ISLAND ?</h1>

In [21]:
early_bird['species'] == 'Adelie'

0       True
1       True
2       True
3       True
4       True
       ...
339    False
340    False
341    False
342    False
343    False
Name: species, Length: 344, dtype: bool

In [22]:
early_bird[early_bird['species'] == 'Adelie']

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight_kilo
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.8
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.8
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.4
...,...,...,...,...,...,...,...,...,...
147,Adelie,Dream,36.6,18.4,184.0,3475.0,female,2009,3.5
148,Adelie,Dream,36.0,17.8,195.0,3450.0,female,2009,3.4
149,Adelie,Dream,37.8,18.1,193.0,3750.0,male,2009,3.8
150,Adelie,Dream,36.0,17.1,187.0,3700.0,female,2009,3.7
151,Adelie,Dream,41.5,18.5,201.0,4000.0,male,2009,4.0

<h1> ADELIE ON DIFFERENT ISLAND </h1>

In [23]:
early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Biscoe')]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight_kilo
20,Adelie,Biscoe,37.8,18.3,174.0,3400.0,female,2007,3.4
21,Adelie,Biscoe,37.7,18.7,180.0,3600.0,male,2007,3.6
22,Adelie,Biscoe,35.9,19.2,189.0,3800.0,female,2007,3.8
23,Adelie,Biscoe,38.2,18.1,185.0,3950.0,male,2007,4.0
24,Adelie,Biscoe,38.8,17.2,180.0,3800.0,male,2007,3.8
25,Adelie,Biscoe,35.3,18.9,187.0,3800.0,female,2007,3.8
26,Adelie,Biscoe,40.6,18.6,183.0,3550.0,male,2007,3.6
27,Adelie,Biscoe,40.5,17.9,187.0,3200.0,female,2007,3.2
28,Adelie,Biscoe,37.9,18.6,172.0,3150.0,female,2007,3.2
29,Adelie,Biscoe,40.5,18.9,180.0,3950.0,male,2007,4.0
50,Adelie,Biscoe,39.6,17.7,186.0,3500.0,female,2008,3.5
51,Adelie,Biscoe,40.1,18.9,188.0,4300.0,male,2008,4.3
52,Adelie,Biscoe,35.0,17.9,190.0,3450.0,female,2008,3.4
53,Adelie,Biscoe,42.0,19.5,200.0,4050.0,male,2008,4.0
54,Adelie,Biscoe,34.5,18.1,187.0,2900.0,female,2008,2.9
55,Adelie,Biscoe,41.4,18.6,191.0,3700.0,male,2008,3.7
56,Adelie,Biscoe,39.0,17.5,186.0,3550.0,female,2008,3.6
57,Adelie,Biscoe,40.6,18.8,193.0,3800.0,male,2008,3.8
58,Adelie,Biscoe,36.5,16.6,181.0,2850.0,female,2008,2.8
59,Adelie,Biscoe,37.6,19.1,194.0,3750.0,male,2008,3.8
60,Adelie,Biscoe,35.7,16.9,185.0,3150.0,female,2008,3.2
61,Adelie,Biscoe,41.3,21.1,195.0,4400.0,male,2008,4.4
62,Adelie,Biscoe,37.6,17.0,185.0,3600.0,female,2008,3.6
63,Adelie,Biscoe,41.1,18.2,192.0,4050.0,male,2008,4.0
64,Adelie,Biscoe,36.4,17.1,184.0,2850.0,female,2008,2.8
65,Adelie,Biscoe,41.6,18.0,192.0,3950.0,male,2008,4.0
66,Adelie,Biscoe,35.5,16.2,195.0,3350.0,female,2008,3.4
67,Adelie,Biscoe,41.1,19.1,188.0,4100.0,male,2008,4.1
100,Adelie,Biscoe,35.0,17.9,192.0,3725.0,female,2009,3.7
101,Adelie,Biscoe,41.0,20.0,203.0,4725.0,male,2009,4.7
102,Adelie,Biscoe,37.7,16.0,183.0,3075.0,female,2009,3.1
103,Adelie,Biscoe,37.8,20.0,190.0,4250.0,male,2009,4.2
104,Adelie,Biscoe,37.9,18.6,193.0,2925.0,female,2009,2.9
105,Adelie,Biscoe,39.7,18.9,184.0,3550.0,male,2009,3.6
106,Adelie,Biscoe,38.6,17.2,199.0,3750.0,female,2009,3.8
107,Adelie,Biscoe,38.2,20.0,190.0,3900.0,male,2009,3.9
108,Adelie,Biscoe,38.1,17.0,181.0,3175.0,female,2009,3.2
109,Adelie,Biscoe,43.2,19.0,197.0,4775.0,male,2009,4.8
110,Adelie,Biscoe,38.1,16.5,198.0,3825.0,female,2009,3.8
111,Adelie,Biscoe,45.6,20.3,191.0,4600.0,male,2009,4.6
112,Adelie,Biscoe,39.7,17.7,193.0,3200.0,female,2009,3.2
113,Adelie,Biscoe,42.2,19.5,197.0,4275.0,male,2009,4.3
114,Adelie,Biscoe,39.6,20.7,191.0,3900.0,female,2009,3.9
115,Adelie,Biscoe,42.7,18.3,196.0,4075.0,male,2009,4.1

In [24]:
early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Biscoe')].count()

species              44
island               44
bill_length_mm       44
bill_depth_mm        44
flipper_length_mm    44
body_mass_g          44
sex                  44
year                 44
weight_kilo          44
dtype: int64

In [25]:
early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Torgersen')]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight_kilo
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007,3.8
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007,3.8
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007,3.2
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007,3.4
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007,3.6
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,female,2007,3.6
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,male,2007,4.7
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN,2007,3.5
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN,2007,4.2
10,Adelie,Torgersen,37.8,17.1,186.0,3300.0,NaN,2007,3.3
11,Adelie,Torgersen,37.8,17.3,180.0,3700.0,NaN,2007,3.7
12,Adelie,Torgersen,41.1,17.6,182.0,3200.0,female,2007,3.2
13,Adelie,Torgersen,38.6,21.2,191.0,3800.0,male,2007,3.8
14,Adelie,Torgersen,34.6,21.1,198.0,4400.0,male,2007,4.4
15,Adelie,Torgersen,36.6,17.8,185.0,3700.0,female,2007,3.7
16,Adelie,Torgersen,38.7,19.0,195.0,3450.0,female,2007,3.4
17,Adelie,Torgersen,42.5,20.7,197.0,4500.0,male,2007,4.5
18,Adelie,Torgersen,34.4,18.4,184.0,3325.0,female,2007,3.3
19,Adelie,Torgersen,46.0,21.5,194.0,4200.0,male,2007,4.2
68,Adelie,Torgersen,35.9,16.6,190.0,3050.0,female,2008,3.0
69,Adelie,Torgersen,41.8,19.4,198.0,4450.0,male,2008,4.4
70,Adelie,Torgersen,33.5,19.0,190.0,3600.0,female,2008,3.6
71,Adelie,Torgersen,39.7,18.4,190.0,3900.0,male,2008,3.9
72,Adelie,Torgersen,39.6,17.2,196.0,3550.0,female,2008,3.6
73,Adelie,Torgersen,45.8,18.9,197.0,4150.0,male,2008,4.2
74,Adelie,Torgersen,35.5,17.5,190.0,3700.0,female,2008,3.7
75,Adelie,Torgersen,42.8,18.5,195.0,4250.0,male,2008,4.2
76,Adelie,Torgersen,40.9,16.8,191.0,3700.0,female,2008,3.7
77,Adelie,Torgersen,37.2,19.4,184.0,3900.0,male,2008,3.9
78,Adelie,Torgersen,36.2,16.1,187.0,3550.0,female,2008,3.6
79,Adelie,Torgersen,42.1,19.1,195.0,4000.0,male,2008,4.0
80,Adelie,Torgersen,34.6,17.2,189.0,3200.0,female,2008,3.2
81,Adelie,Torgersen,42.9,17.6,196.0,4700.0,male,2008,4.7
82,Adelie,Torgersen,36.7,18.8,187.0,3800.0,female,2008,3.8
83,Adelie,Torgersen,35.1,19.4,193.0,4200.0,male,2008,4.2
116,Adelie,Torgersen,38.6,17.0,188.0,2900.0,female,2009,2.9
117,Adelie,Torgersen,37.3,20.5,199.0,3775.0,male,2009,3.8
118,Adelie,Torgersen,35.7,17.0,189.0,3350.0,female,2009,3.4
119,Adelie,Torgersen,41.1,18.6,189.0,3325.0,male,2009,3.3
120,Adelie,Torgersen,36.2,17.2,187.0,3150.0,female,2009,3.2
121,Adelie,Torgersen,37.7,19.8,198.0,3500.0,male,2009,3.5
122,Adelie,Torgersen,40.2,17.0,176.0,3450.0,female,2009,3.4
123,Adelie,Torgersen,41.4,18.5,202.0,3875.0,male,2009,3.9
124,Adelie,Torgersen,35.2,15.9,186.0,3050.0,female,2009,3.0
125,Adelie,Torgersen,40.6,19.0,199.0,4000.0,male,2009,4.0
126,Adelie,Torgersen,38.8,17.6,191.0,3275.0,female,2009,3.3
127,Adelie,Torgersen,41.5,18.3,195.0,4300.0,male,2009,4.3
128,Adelie,Torgersen,39.0,17.1,191.0,3050.0,female,2009,3.0
129,Adelie,Torgersen,44.1,18.0,210.0,4000.0,male,2009,4.0
130,Adelie,Torgersen,38.5,17.9,190.0,3325.0,female,2009,3.3
131,Adelie,Torgersen,43.1,19.2,197.0,3500.0,male,2009,3.5

In [26]:
early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Torgersen')].count()

species              52
island               52
bill_length_mm       51
bill_depth_mm        51
flipper_length_mm    51
body_mass_g          51
sex                  47
year                 52
weight_kilo          51
dtype: int64

In [27]:
early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Dream')]

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year,weight_kilo
30,Adelie,Dream,39.5,16.7,178.0,3250.0,female,2007,3.2
31,Adelie,Dream,37.2,18.1,178.0,3900.0,male,2007,3.9
32,Adelie,Dream,39.5,17.8,188.0,3300.0,female,2007,3.3
33,Adelie,Dream,40.9,18.9,184.0,3900.0,male,2007,3.9
34,Adelie,Dream,36.4,17.0,195.0,3325.0,female,2007,3.3
35,Adelie,Dream,39.2,21.1,196.0,4150.0,male,2007,4.2
36,Adelie,Dream,38.8,20.0,190.0,3950.0,male,2007,4.0
37,Adelie,Dream,42.2,18.5,180.0,3550.0,female,2007,3.6
38,Adelie,Dream,37.6,19.3,181.0,3300.0,female,2007,3.3
39,Adelie,Dream,39.8,19.1,184.0,4650.0,male,2007,4.6
40,Adelie,Dream,36.5,18.0,182.0,3150.0,female,2007,3.2
41,Adelie,Dream,40.8,18.4,195.0,3900.0,male,2007,3.9
42,Adelie,Dream,36.0,18.5,186.0,3100.0,female,2007,3.1
43,Adelie,Dream,44.1,19.7,196.0,4400.0,male,2007,4.4
44,Adelie,Dream,37.0,16.9,185.0,3000.0,female,2007,3.0
45,Adelie,Dream,39.6,18.8,190.0,4600.0,male,2007,4.6
46,Adelie,Dream,41.1,19.0,182.0,3425.0,male,2007,3.4
47,Adelie,Dream,37.5,18.9,179.0,2975.0,NaN,2007,3.0
48,Adelie,Dream,36.0,17.9,190.0,3450.0,female,2007,3.4
49,Adelie,Dream,42.3,21.2,191.0,4150.0,male,2007,4.2
84,Adelie,Dream,37.3,17.8,191.0,3350.0,female,2008,3.4
85,Adelie,Dream,41.3,20.3,194.0,3550.0,male,2008,3.6
86,Adelie,Dream,36.3,19.5,190.0,3800.0,male,2008,3.8
87,Adelie,Dream,36.9,18.6,189.0,3500.0,female,2008,3.5
88,Adelie,Dream,38.3,19.2,189.0,3950.0,male,2008,4.0
89,Adelie,Dream,38.9,18.8,190.0,3600.0,female,2008,3.6
90,Adelie,Dream,35.7,18.0,202.0,3550.0,female,2008,3.6
91,Adelie,Dream,41.1,18.1,205.0,4300.0,male,2008,4.3
92,Adelie,Dream,34.0,17.1,185.0,3400.0,female,2008,3.4
93,Adelie,Dream,39.6,18.1,186.0,4450.0,male,2008,4.4
94,Adelie,Dream,36.2,17.3,187.0,3300.0,female,2008,3.3
95,Adelie,Dream,40.8,18.9,208.0,4300.0,male,2008,4.3
96,Adelie,Dream,38.1,18.6,190.0,3700.0,female,2008,3.7
97,Adelie,Dream,40.3,18.5,196.0,4350.0,male,2008,4.4
98,Adelie,Dream,33.1,16.1,178.0,2900.0,female,2008,2.9
99,Adelie,Dream,43.2,18.5,192.0,4100.0,male,2008,4.1
132,Adelie,Dream,36.8,18.5,193.0,3500.0,female,2009,3.5
133,Adelie,Dream,37.5,18.5,199.0,4475.0,male,2009,4.5
134,Adelie,Dream,38.1,17.6,187.0,3425.0,female,2009,3.4
135,Adelie,Dream,41.1,17.5,190.0,3900.0,male,2009,3.9
136,Adelie,Dream,35.6,17.5,191.0,3175.0,female,2009,3.2
137,Adelie,Dream,40.2,20.1,200.0,3975.0,male,2009,4.0
138,Adelie,Dream,37.0,16.5,185.0,3400.0,female,2009,3.4
139,Adelie,Dream,39.7,17.9,193.0,4250.0,male,2009,4.2
140,Adelie,Dream,40.2,17.1,193.0,3400.0,female,2009,3.4
141,Adelie,Dream,40.6,17.2,187.0,3475.0,male,2009,3.5
142,Adelie,Dream,32.1,15.5,188.0,3050.0,female,2009,3.0
143,Adelie,Dream,40.7,17.0,190.0,3725.0,male,2009,3.7
144,Adelie,Dream,37.3,16.8,192.0,3000.0,female,2009,3.0
145,Adelie,Dream,39.0,18.7,185.0,3650.0,male,2009,3.6
146,Adelie,Dream,39.2,18.6,190.0,4250.0,male,2009,4.2
147,Adelie,Dream,36.6,18.4,184.0,3475.0,female,2009,3.5
148,Adelie,Dream,36.0,17.8,195.0,3450.0,female,2009,3.4
149,Adelie,Dream,37.8,18.1,193.0,3750.0,male,2009,3.8
150,Adelie,Dream,36.0,17.1,187.0,3700.0,female,2009,3.7
151,Adelie,Dream,41.5,18.5,201.0,4000.0,male,2009,4.0

In [28]:
early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Dream')].count()

species              56
island               56
bill_length_mm       56
bill_depth_mm        56
flipper_length_mm    56
body_mass_g          56
sex                  55
year                 56
weight_kilo          56
dtype: int64

In [29]:
biscoe_adel = early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Biscoe')]

In [30]:
dream_adel = early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Dream')]

In [31]:
tor_adel = early_bird[(early_bird['species'] == 'Adelie') & (early_bird['island'] == 'Torgersen')]

In [32]:
np.round(biscoe_adel['weight_kilo'].mean() , 1)

np.float64(3.7)

In [33]:
np.round(dream_adel['weight_kilo'].mean(), 1)

np.float64(3.7)

In [34]:
np.round(tor_adel['weight_kilo'].mean() ,1)

np.float64(3.7)

<h1> INSIGHT 1 </h1>
<h2> Adelie does not live exclusively in Biscoe Island. Adelie lives in all island in the Dataset. </h2>

<h1> INSIGHT 4 </h1>
<h2> Adelie weight relatively despite living in different island. </h2> </h2>

<h1> INSIGHT 4.1 </h1>
<h2> The average weight of Adelie in Biscoe is 3.7 kilograms. </h2>

<h1> INSIGHT 4.2 </h1>
<h2> The average weight of Adelie in Dream is 3.7 kilograms. </h2>

<h1> INSIGHT 4.3 </h1>
<h2> The average weight of Adelie in Torgersen is 3.7 kilograms. </h2>

<h1> GENTO SPECIES </h1

In [35]:
early_bird[(early_bird['species'] == 'Gentoo') & (early_bird['island'] == 'Biscoe')].count()

species              124
island               124
bill_length_mm       123
bill_depth_mm        123
flipper_length_mm    123
body_mass_g          123
sex                  119
year                 124
weight_kilo          123
dtype: int64

In [36]:
early_bird[(early_bird['species'] == 'Gentoo') & (early_bird['island'] == 'Dream')].count()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight_kilo          0
dtype: int64

In [37]:
early_bird[(early_bird['species'] == 'Gentoo') & (early_bird['island'] == 'Torgersen')].count()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight_kilo          0
dtype: int64

In [38]:
gentoo_biscoe = early_bird[(early_bird['species'] == 'Gentoo') & (early_bird['island'] == 'Biscoe')]

In [39]:
np.round(gentoo_biscoe['weight_kilo'].mean(),1)

np.float64(5.1)

<h1> INSIGHT 2 </h1>
<h2> Gentoo species live exclusively in the Biscoe Island. </h2>

<h1> INSIGHT 5 </h1>
<h2> The Gentoo species has an average 5.1 kilograms</h2>

<h1> Chinstrap Species </h1>

In [40]:
early_bird[(early_bird['species'] == 'Chinstrap') & (early_bird['island'] == 'Biscoe')].count()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight_kilo          0
dtype: int64

In [41]:
early_bird[(early_bird['species'] == 'Chinstrap') & (early_bird['island'] == 'Torgersen')].count()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
year                 0
weight_kilo          0
dtype: int64

In [42]:
early_bird[(early_bird['species'] == 'Chinstrap') & (early_bird['island'] == 'Dream')].count()

species              68
island               68
bill_length_mm       68
bill_depth_mm        68
flipper_length_mm    68
body_mass_g          68
sex                  68
year                 68
weight_kilo          68
dtype: int64

In [43]:
chins_dream = early_bird[(early_bird['species'] == 'Chinstrap') & (early_bird['island'] == 'Dream')]

In [44]:
np.round(chins_dream['weight_kilo'].mean(),1)

np.float64(3.7)

<h1> INSIGHT 3 </h1>
<h2> Chinstrap species live exclusively in the Dream Island. </h2>

<h1> INSIGHT 6 </h1>
<h2> Chinstrap species has an average weight of 3.7 kilograms.</h2>

<h1> INSIGHT 7 </h1>
<h3> Gentoo is the heaviest species compared to Adelie and Chinstrap  </h3>

In [45]:
penguin_insight7 = np.round(early_bird.groupby('species')['weight_kilo'].mean(), 1)

In [46]:
penguin_insight7

species
Adelie       3.7
Chinstrap    3.7
Gentoo       5.1
Name: weight_kilo, dtype: float64

<h1> The use of GROUPBY </h1>

In [47]:
penguin_insight8 = early_bird.groupby(['species','island','sex']).count()

In [48]:
penguin_insight8

                            bill_length_mm  bill_depth_mm  flipper_length_mm  \
species   island    sex
Adelie    Biscoe    female              22             22                 22
                    male                22             22                 22
          Dream     female              27             27                 27
                    male                28             28                 28
          Torgersen female              24             24                 24
                    male                23             23                 23
Chinstrap Dream     female              34             34                 34
                    male                34             34                 34
Gentoo    Biscoe    female              58             58                 58
                    male                61             61                 61

                            body_mass_g  year  weight_kilo
species   island    sex
Adelie    Biscoe    female           22    22           22
                    male             22    22           22
          Dream     female           27    27           27
                    male             28    28           28
          Torgersen female           24    24           24
                    male             23    23           23
Chinstrap Dream     female           34    34           34
                    male             34    34           34
Gentoo    Biscoe    female           58    58           58
                    male             61    61           61

In [49]:
penguin_insight8 = early_bird.groupby(['species','island','sex']).size()

In [50]:
penguin_insight8

species    island     sex
Adelie     Biscoe     female    22
                      male      22
           Dream      female    27
                      male      28
           Torgersen  female    24
                      male      23
Chinstrap  Dream      female    34
                      male      34
Gentoo     Biscoe     female    58
                      male      61
dtype: int64

<h1> Which is heavier, amongst the penguin species, Male or Female </h1>

In [51]:
pengui_insight9 = early_bird.groupby(['species','sex'])['weight_kilo'].mean()

In [52]:
pengui_insight9

species    sex
Adelie     female    3.367123
           male      4.047945
Chinstrap  female    3.523529
           male      3.938235
Gentoo     female    4.681034
           male      5.485246
Name: weight_kilo, dtype: float64

In [53]:
pengui_insight9.unstack()

sex          female      male
species
Adelie     3.367123  4.047945
Chinstrap  3.523529  3.938235
Gentoo     4.681034  5.485246

<h1> 10. Correlation between Bill Length and Bill Depth </h1>

In [54]:
depth_length = early_bird['bill_length_mm'].corr(early_bird['bill_depth_mm'])

In [55]:
depth_length

np.float64(-0.23505287035553257)

<h1> INSIGHT 10 </h1>
<h3> There is no correlation between Bill Length and Bill Depth</h3>

<h1>Syntax Requirement</h1>
    <ul>
        <li>Variable Name for correlation Result</li>
        <li> First Column </li>
        <li> corr function</li>
        <li> secong column </li>
    </ul>

<h1> 11. Correlation between body mass and flipper length </h1>

In [56]:
body_length = early_bird['flipper_length_mm'].corr(early_bird['body_mass_g'])

In [57]:
early_bird.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    object
 1   island             344 non-null    object
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object
 7   year               344 non-null    int64
 8   weight_kilo        342 non-null    float64
dtypes: float64(5), int64(1), object(3)
memory usage: 24.3+ KB

In [58]:
body_length

np.float64(0.8712017673060113)

<h1> INSIGTH 11 </h1>
<h3> There is a correlation between Bill Length and Bill Depth </h3>

<h1> 12. Correlation between bill length and flipper length </h1>

In [59]:
body_flip = early_bird['bill_length_mm'].corr(early_bird['flipper_length_mm'])

In [60]:
body_flip

np.float64(0.6561813407464278)

<h1> INSIGTH 12 </h1>
<h3> There is a correlation between Bill Length and Flipper Length </h3>

<h1> 13. Correlation between bill length and body mass </h1>

In [61]:
body_length = early_bird['bill_length_mm'].corr(early_bird['body_mass_g'])

In [62]:
body_length

np.float64(0.5951098244376303)

<h1> INSIGTH 13 </h1>
<h3> There is a correlation between Bill Length and Body Mass </h3>

<h1> 14. Correlation between bill depth and body mass </h1>

In [63]:
body_depth = early_bird['bill_depth_mm'].corr(early_bird['body_mass_g'])

In [64]:
body_depth

np.float64(-0.47191562118606645)

<h1> INSIGHT 14 </h1>
<h3> There is no correlation between Bill Depth and Body Mass </h3>

<h1>15. Correlation between bill depth and bill length of each species </h1>

In [65]:
adelie = early_bird[early_bird['species'] == 'Adelie']

In [66]:
gentoo = early_bird[early_bird['species'] == 'Gentoo']

In [67]:
chins = early_bird[early_bird['species'] == 'Chinstrap']

In [68]:
adelie['bill_length_mm'].corr(adelie['bill_depth_mm'])

np.float64(0.39149169183587657)

In [69]:
gentoo['bill_length_mm'].corr(gentoo['bill_depth_mm'])

np.float64(0.6433839465253387)

In [70]:
chins['bill_length_mm'].corr(chins['bill_depth_mm'])

np.float64(0.6535362081800429)

<h3> Insights: Only Adelie's bill length is not affected by its bill depth </h3>

<h1>Correlational Analysis between Qualitative Data and Qualitative </h1>

<h1> Package name : Science Python - Scipy </h1>

In [71]:
pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: scipy in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (1.15.1)
Requirement already satisfied: numpy<2.5,>=1.23.5 in c:\users\lab5-studentpc03\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from scipy) (2.2.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: C:\Users\LAB5-StudentPC03\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

<h1>Testing Correlation using One way Anova , Analysis of Variance </h1>

In [72]:
from scipy.stats import f_oneway

<h1>Syntax Requirement</h1>
    <ul>
        <li>specify the value for categorical</li>
        <li>specify the quantitative data </li>
    </ul>

In [73]:
#male
#female

f_stats, p_value = f_oneway(early_bird[early_bird['sex'] == 'male']['body_mass_g'],
                            early_bird[early_bird['sex'] == 'female']['body_mass_g'])

print(p_value)

4.897246751596225e-16